### ISSUE TITLE
Wrong B-Field parameters for Jansson12b and 12c cases

### ISSUE THREAD

**Issue by ap-gautham** [me-manu/gammaALPs#2]
In Jansson 12b and 12c cases, some of the B-Field spiral arm parameters are changed. However, b7 is kept unchanged. Since b7 is a constrained parameter, fixed due to the other 7 parameters(JF-1204.3662 section:5.1.1), this has to change as well, I think. Is this a bug?

**Comment by me-manu** [comment]
Hi @ap-gautham, 

Sorry for taking so long with this - I somehow thought that I had already fixed this, but I had only assigned myself to fix it. Anyway, you're right, b8 should be calculated from the other spiral arm fields, this is fixed now. Also, I just released an official release of the code and you can now use pip to install it. There's also now a full documentation at https://gammaalps.readthedocs.io which you hopefully find helpful. Let me know if there are any other issues.
