### ISSUE TITLE
example_single_cell_and_gmf.ipynb

### ISSUE THREAD

**Issue by Hyperthetical** [me-manu/gammaALPs#5]
Following issue occurred when testing the perseus section of the notebook
![perseus_error](https://user-images.githubusercontent.com/35954338/104888576-99b8c180-5975-11eb-9a75-30f83191fdeb.png)

**Comment by Hyperthetical** [comment]
Generated on windows, will see if its windows specific

**Comment by me-manu** [comment]
Thanks @Hyperthetical for reporting this. Yes, please check if the errors occurs on windows only. I haven't encountered it using my anaconda python installation on Mac and Linux. Anyway, I should probably put a safeguard for this into place.

**Comment by Hyperthetical** [comment]
Doesn't appear on linux, it is windows only

**Comment by me-manu** [comment]
OK. Could you change line 296 in `gammaALPs.bfields.gauss.py` to this:
```
seeds = randint(2 ** (math.log(sys.maxsize * 2 + 2) / math.log(2) / 2) - 1, size=nsim)
```
and add the following imports at the top of `gauss.py`:
```
import math
import sys
```
and try again on your windows machine? This hopefully protects against the above error. However, I don't have a windows machine to test it. Thanks a lot!

**Comment by Hyperthetical** [comment]
Same error still, adding a dtype argument to the randint doesn't fix it either.

**Comment by me-manu** [comment]
Did some more digging on stackoverflow. Could you try this line?
```
seeds = randint(2 ** (math.log(sys.maxsize * 2 + 2) / math.log(2) / 2 - 1) - 1, size=nsim)
```
If that doesn't work either, I'll put in some brute force check to reduce the high end. Thanks again!

**Comment by Hyperthetical** [comment]
Still generating the same error

**Comment by me-manu** [comment]
Hi again, 
Here's another try that hopefully works. Again, could you replace the offending line with the following lines (and again `import sys` and `import math` at the top:
```
if sys.platform == "win32":
    high = 2**(math.log2(sys.maxsize) / 2)
else:
    high = 2**(math.log2(sys.maxsize))
seeds = randint(high, size=nsim)
```

**Comment by me-manu** [comment]
@Hyperthetical Did you have time to check the new suggested solution? I'm planning on closing this and adding CI tests for windows as well to avoid situations like this in the future. Thanks!

**Comment by Hyperthetical** [comment]
I checked it, it now works fine

Dr Geoff Beck
Senior lecturer in physics
University of the Witwatersrand

**Comment by me-manu** [comment]
OK, I just merged a pull request that fixes this. Windows tests are also included in Travis now.
