### ISSUE TITLE
Create an entry in zenodo for gammaALPs

### ISSUE THREAD

**Issue by cosimoNigro** [me-manu/gammaALPs#9]
Hello @me-manu,

It is not clear from the `README` or the docs how to properly acknowledge the usage of the code.
I'd suggest you to create an entry in [zenodo](https://zenodo.org/).

Users - like me - will be able to properly reference the code when they use it in a scientific paper.
It is super-easy to do it with an already existing GitHub repo, you can check the zenodo record of [one of my codes](https://zenodo.org/record/4311271), simply imported from git.
You can generate a DOI for each release, so users can cite the exact version they are using.
Additionally there is a new feature keeping track of the papers citing the code (see "Citations" at the bottom of the page).
If you are interested I can help you creating it (it's few steps from zenodo).

Cheers,
Cosimo

**Comment by me-manu** [comment]
Thanks @cosimoNigro, that sounds like a great idea. We are planning on a contribution to the ICRC, which people could reference. But a zenodo entry in addition would make sense, too, I believe. If you could point me to a good tutorial describing the necessary steps that would be much appreciated.

**Comment by cosimoNigro** [comment]
I don't know if there is a tutorial, but it's quite simple.
1) log-in to zenodo, I suggest you to log-in with your GitHub account, this way the accoutns should be automatically linked.
2) click on your profile (top right button with your user or e-mail), you should see something like this
![Screenshot from 2021-03-02 09-18-49](https://user-images.githubusercontent.com/26409711/109619083-a0238700-7b38-11eb-982d-be3f4ab9406f.png)
3) if you go to the "GitHub" tab at the bottom of the profile menu, you should see this menu with the giant switch. 
Once you flip all your git repos will appear in the "Repositories" list. You can choose which one to enable, i.e. which one to use to create the entry in zendo, in this case `me-manu/gammaALPs` (flip the little switch besides the repo name). 
As specified by the instructions, a release is necessary for zenodo to start tracking and this is already available in your code  
![Screenshot from 2021-03-02 09-19-32](https://user-images.githubusercontent.com/26409711/109619261-da8d2400-7b38-11eb-976b-3038c2a7f8fe.png)
4) After the repo is enabled you should get your DOI and the zenodo page. From now on all the release you create will generate a new entry in zenodo (another DOI but all linked in the same page).
![Screenshot from 2021-03-02 09-33-33](https://user-images.githubusercontent.com/26409711/109620665-70757e80-7b3a-11eb-9032-f6a7fa59c65a.png)

**Note** that when the zenodo entry is created whatever text you put in the latest tag is copied in the main page (in your case "Extended testing and windows support"). What I usually do is I copy the text in README.md in the main page (click the orange `Edit` button) such that each version of the code contains a general overview of it.

If you need help with any of this steps write here,
Cheers

**Comment by me-manu** [comment]
Finally got around to add the repo to zenodo: https://zenodo.org/badge/latestdoi/96319590
